licenseKey = ""
rpcUrl = ""
grpcUrl = ""
wssUrl = ""
webhookUrl = ""
blockEngineURLLocation = "amsterdam" #amsterdam,frankfurt,newyork,tokyo
TPS = 100
extraRPCS = []
pnlDelayMS = 0 # to enable pnl, set to higher than 0. not enabled in wss. only using grpc
grpcHeaders = ""
[copyTrader]
turbo=true
global_maximum_buys_per_token = 25
temporal = false
jito = false
circular = false
bloxroute = false
nextblock = true
nextblockLocation = "frankfurt" # frankfurt / newyork
temporalLocation = "http://ams1.nozomi.temporal.xyz/?c=" #amsterdam / frankfurt / useast
temporal_apiKey = ""
nextblock_apiKey = ""
circular_apiKey = ""
bloxroute_url = "https://ny.solana.dex.blxrbdn.com/api/v2/submit" # make sure it ends with /api/v2/submit
bloxroute_api_key = ""
buy_tipFee = 0.001
sell_tipFee = 0.001

heliusUrl = "anything" # if u dont want to use it, fill any random url. DO NOT LEAVE EMPTY
getTransactionDelayMS = 10
getTransactionRetries = 75
getAccountInfoDelayMS = 10
getAccountInfoRetries = 75

