// Code generated by MockGen. DO NOT EDIT.
// Source: .\models\interfaces.go
//
// Generated by this command:
//
//	mockgen -source=.\models\interfaces.go -destination=mock_client.go
//

// Package mock_models is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	solana "github.com/gagliardetto/solana-go"
	rpc "github.com/gagliardetto/solana-go/rpc"
	gomock "go.uber.org/mock/gomock"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// GetAccountInfoWithOpts mocks base method.
func (m *MockIClient) GetAccountInfoWithOpts(ctx context.Context, account solana.PublicKey, opts *rpc.GetAccountInfoOpts) (*rpc.GetAccountInfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountInfoWithOpts", ctx, account, opts)
	ret0, _ := ret[0].(*rpc.GetAccountInfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountInfoWithOpts indicates an expected call of GetAccountInfoWithOpts.
func (mr *MockIClientMockRecorder) GetAccountInfoWithOpts(ctx, account, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountInfoWithOpts", reflect.TypeOf((*MockIClient)(nil).GetAccountInfoWithOpts), ctx, account, opts)
}

// GetLatestBlockhash mocks base method.
func (m *MockIClient) GetLatestBlockhash(ctx context.Context, commitment rpc.CommitmentType) (*rpc.GetLatestBlockhashResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlockhash", ctx, commitment)
	ret0, _ := ret[0].(*rpc.GetLatestBlockhashResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlockhash indicates an expected call of GetLatestBlockhash.
func (mr *MockIClientMockRecorder) GetLatestBlockhash(ctx, commitment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlockhash", reflect.TypeOf((*MockIClient)(nil).GetLatestBlockhash), ctx, commitment)
}

// GetSignatureStatuses mocks base method.
func (m *MockIClient) GetSignatureStatuses(ctx context.Context, searchTransactionHistory bool, transactionSignatures ...solana.Signature) (*rpc.GetSignatureStatusesResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, searchTransactionHistory}
	for _, a := range transactionSignatures {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSignatureStatuses", varargs...)
	ret0, _ := ret[0].(*rpc.GetSignatureStatusesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignatureStatuses indicates an expected call of GetSignatureStatuses.
func (mr *MockIClientMockRecorder) GetSignatureStatuses(ctx, searchTransactionHistory any, transactionSignatures ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, searchTransactionHistory}, transactionSignatures...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignatureStatuses", reflect.TypeOf((*MockIClient)(nil).GetSignatureStatuses), varargs...)
}

// GetTokenAccountBalance mocks base method.
func (m *MockIClient) GetTokenAccountBalance(ctx context.Context, account solana.PublicKey, commitment rpc.CommitmentType) (*rpc.GetTokenAccountBalanceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenAccountBalance", ctx, account, commitment)
	ret0, _ := ret[0].(*rpc.GetTokenAccountBalanceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenAccountBalance indicates an expected call of GetTokenAccountBalance.
func (mr *MockIClientMockRecorder) GetTokenAccountBalance(ctx, account, commitment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenAccountBalance", reflect.TypeOf((*MockIClient)(nil).GetTokenAccountBalance), ctx, account, commitment)
}

// GetTokenAccountsByOwner mocks base method.
func (m *MockIClient) GetTokenAccountsByOwner(ctx context.Context, owner solana.PublicKey, conf *rpc.GetTokenAccountsConfig, opts *rpc.GetTokenAccountsOpts) (*rpc.GetTokenAccountsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenAccountsByOwner", ctx, owner, conf, opts)
	ret0, _ := ret[0].(*rpc.GetTokenAccountsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenAccountsByOwner indicates an expected call of GetTokenAccountsByOwner.
func (mr *MockIClientMockRecorder) GetTokenAccountsByOwner(ctx, owner, conf, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenAccountsByOwner", reflect.TypeOf((*MockIClient)(nil).GetTokenAccountsByOwner), ctx, owner, conf, opts)
}

// GetTransaction mocks base method.
func (m *MockIClient) GetTransaction(ctx context.Context, txSig solana.Signature, opts *rpc.GetTransactionOpts) (*rpc.GetTransactionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, txSig, opts)
	ret0, _ := ret[0].(*rpc.GetTransactionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockIClientMockRecorder) GetTransaction(ctx, txSig, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockIClient)(nil).GetTransaction), ctx, txSig, opts)
}

// SendTransactionWithOpts mocks base method.
func (m *MockIClient) SendTransactionWithOpts(ctx context.Context, transaction *solana.Transaction, opts rpc.TransactionOpts) (solana.Signature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTransactionWithOpts", ctx, transaction, opts)
	ret0, _ := ret[0].(solana.Signature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTransactionWithOpts indicates an expected call of SendTransactionWithOpts.
func (mr *MockIClientMockRecorder) SendTransactionWithOpts(ctx, transaction, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransactionWithOpts", reflect.TypeOf((*MockIClient)(nil).SendTransactionWithOpts), ctx, transaction, opts)
}

// SimulateTransactionWithOpts mocks base method.
func (m *MockIClient) SimulateTransactionWithOpts(ctx context.Context, transaction *solana.Transaction, opts *rpc.SimulateTransactionOpts) (*rpc.SimulateTransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SimulateTransactionWithOpts", ctx, transaction, opts)
	ret0, _ := ret[0].(*rpc.SimulateTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SimulateTransactionWithOpts indicates an expected call of SimulateTransactionWithOpts.
func (mr *MockIClientMockRecorder) SimulateTransactionWithOpts(ctx, transaction, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SimulateTransactionWithOpts", reflect.TypeOf((*MockIClient)(nil).SimulateTransactionWithOpts), ctx, transaction, opts)
}
