package db

import (
	"Zed/models"
	"context"
	"encoding/json"
	"fmt"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos"
	"github.com/google/uuid"
	"github.com/gookit/slog"
)

var databaseName = "Zed"
var licensesContainer = "ItemsContainer"
var transactionsContainer = "TransactionsContainer"

type Connection struct {
	Conn              *azcosmos.Client
	containerLicenses *azcosmos.ContainerClient
	containerTrans    *azcosmos.ContainerClient
}

type License struct {
	ID         string `json:"id"`
	LicenseKey string `json:"LicenseKey"`
	DiscordID  string `json:"DiscordID"`
	IP         string `json:"HardwareID,omitempty"` // omitempty to handle null values. HardwareID because this was the original field name. Now it's IP rather than HardwareID.
	StartDate  int64  `json:"StartDate"`
	EndDate    int64  `json:"EndDate"`
	Status     string `json:"Status"`
}

func NewDBConnection(whitelabel string) (Connection, error) {
	var err error
	// Set up the Cosmos DB client
	endpoint := "https://<CENSOREDURL>.documents.azure.com:443/"
	cred, err := azcosmos.NewKeyCredential("<CENSOREDKEY>")
	client, err := azcosmos.NewClientWithKey(endpoint, cred, nil)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}

	// Database name is the name of the Whitelabel.
	databaseName = whitelabel
	container, err := client.NewContainer(databaseName, licensesContainer)
	if err != nil {
		return Connection{}, err
	}
	txContainer, err := client.NewContainer(databaseName, transactionsContainer)
	if err != nil {
		return Connection{}, err
	}
	// Define the database and containerLicenses names
	return Connection{Conn: client, containerLicenses: container, containerTrans: txContainer}, nil
}

// GetLicenseData gets the license data from the database, by license key
func (c *Connection) GetLicenseData(licenseKey string) (*License, error) {
	pk := azcosmos.NewPartitionKeyString(licenseKey)
	query := fmt.Sprintf("SELECT * FROM Licenses l WHERE l.LicenseKey = '%s'", licenseKey)
	queryOpts := &azcosmos.QueryOptions{}
	pager := c.containerLicenses.NewQueryItemsPager(query, pk, queryOpts)
	if pager.More() {
		p, err := pager.NextPage(context.Background())
		if err != nil {
			return nil, err
		}
		for _, item := range p.Items {
			var license License
			if err := json.Unmarshal(item, &license); err != nil {
				return nil, fmt.Errorf("failed to unmarshal document: %v", err)
			}
			return &license, nil
		}
	}
	return &License{}, fmt.Errorf("license not found")
}

// RegisterIP registers the ip to the license
func (c *Connection) RegisterIP(license *License, ip string) error {
	license.IP = ip
	licenseJSON, err := json.Marshal(license)
	if err != nil {
		return err
	}
	pk := azcosmos.NewPartitionKeyString(license.LicenseKey)
	_, err = c.containerLicenses.UpsertItem(context.Background(), pk, licenseJSON, nil)
	return nil
}

// LogSwap logs the swap data to the database
// swap does not have an id, so an id is generated by this function to add.
func (c *Connection) LogSwap(swap *models.SwapInfo) {
	if swap == nil || swap.License == "" {
		slog.Debug("Swap or License is nil")
		return
	}
	//Add an ID to the swap
	u := uuid.New().String()
	swap.ID = u
	swapJSON, err := json.Marshal(swap)
	if err != nil {
		slog.Debug(err)
		return
	}
	pk := azcosmos.NewPartitionKeyString(swap.License)
	_, err = c.containerTrans.CreateItem(context.Background(), pk, swapJSON, nil)
	if err != nil {
		slog.Debug(err)
		return
	}
}
